---
title: "Spatial dependence"
---

```{r}
# ðŸ“š Setup ---------------------------------------------------------------------
library(haven)
library(ggstatsplot)
library(ggplot2)
library(cowplot)
```

```{r}
# Load dataset
data <- read_dta("../data/india520.dta")
```

```{r}
# ðŸ— Basic OLS Regression -----------------------------------------------------
model1 <- lm(light_growth96_10rcr_cap ~ log_light96_rcr_cap, data = data)
summary(model1)
```

```{r}
# ðŸ“ Compute regression model for annotation ----------------------------------
model <- lm(light_growth96_10rcr_cap ~ log_light96_rcr_cap, data = data)
slope <- round(coef(model)[2], 3)
rsq   <- round(summary(model)$r.squared, 3)
```

```{r}
#| label: fig-convergence
#| fig-cap: "Regional luminosity convergence across districts in India"
p1 <- ggscatterstats(
  data = data,
  x = log_light96_rcr_cap,
  y = light_growth96_10rcr_cap,
  label.var = district,
  label.expression = (log_light96_rcr_cap > -3 & light_growth96_10rcr_cap < 0) | (log_light96_rcr_cap <-7 & light_growth96_10rcr_cap > 0.2),
  results.subtitle = FALSE,
  xlab = "Ln luminosity per capita 1996",
  ylab = "Growth luminosity per capita 1996-2010"
) +
annotate("label", 
           x = Inf, 
           y = Inf, 
           label = paste("Slope =", slope, "\nRÂ² =", rsq), 
           hjust = 1.1, 
           vjust = 1.5, 
           size = 4)
p1
```

```{r}
#| label: fig-dependence1
#| fig-cap: "Spatial dependence in the growth rate and initial level of luminosity"
p2 <- ggscatterstats(
  data = data,
  x = SL_light_growth96_10rcr_cap,
  y = light_growth96_10rcr_cap,
  results.subtitle = FALSE,
  title = "(a)",
  xlab = "Growth luminosity per capita in neighbors",
  ylab = "Growth luminosity per capita 1996-2010"
)
p2
```

```{r}
#| label: fig-dependence2
#| fig-cap: "Spatial dependence in the growth rate and initial level of luminosity"
p3 <- ggscatterstats(
  data = data,
  x = SL_log_light96_rcr_cap,
  y = log_light96_rcr_cap,
  results.subtitle = FALSE,
  title = "(b)",
  xlab = "Ln luminosity per capita in neighbors",
  ylab = "Ln luminosity per capita 1996"
)
p3
```

```{r}
#| label: fig-dependence-combined
#| fig-cap: "Spatial dependence in the growth rate and initial level of luminosity"

combined <- plot_grid(p2, p3, ncol = 2)
combined
```
