#!/usr/bin/env bash
# clean-render.sh — Clear all Quarto caches and re-render the manuscript
#
# Pipeline:
#   1. Clear all Quarto caches (_freeze, .quarto/embed, embed previews)
#   2. Render REGION PDF separately (4 LaTeX passes for natbib/region.bst)
#   3. Render Standard PDF separately (2 LaTeX passes, scrartcl)
#   4. Render HTML, DOCX, JATS together (JATS creates MECA bundle)
#   5. Strip legacy/ and log/ from MECA bundle
#   6. Upload MECA to GitHub Release (tag: meca-bundle)
#   7. Update MECA link in index.html to point to release URL
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth login)
#
# Use this when:
#   - Underlying data files changed but notebook source didn't
#   - Embed previews are stale despite source changes
#   - You want a guaranteed clean build
set -euo pipefail
cd "$(dirname "$0")/.."

echo "Cleaning Quarto caches..."
rm -rf _freeze/
rm -rf .quarto/embed/
rm -rf .quarto/_freeze/
rm -f notebooks/*.embed-preview.html
rm -rf notebooks/*.embed_files/
rm -f notebooks/*.out.ipynb
rm -f notebooks/*-preview.html

echo "Rendering manuscript..."

# Render REGION PDF separately (requires 4 LaTeX passes with natbib;
# the combined quarto render only runs 2, which drops the REGION template)
echo "  [1/3] REGION journal PDF..."
quarto render index.qmd --to region-ersa/REGION-pdf
# Quarto writes the intermediate LaTeX to index.tex regardless of output-file.
# Rename it now before the standard PDF render overwrites it.
mv index.tex index-REGION.tex

# Render standard PDF separately
echo "  [2/3] Standard PDF..."
quarto render index.qmd --to pdf
# index.tex is now the standard LaTeX source (kept via keep-tex: true)

# Render remaining formats together
echo "  [3/3] HTML, DOCX, JATS..."
quarto render index.qmd --to html --to docx --to jats

# Strip legacy/ from MECA bundle (too large, not needed for replication)
if [ -f index-meca.zip ]; then
  zip -d index-meca.zip "source/legacy/*" 2>/dev/null || true
  zip -d index-meca.zip "source/log/*" 2>/dev/null || true
  echo "  Stripped legacy/ and log/ from MECA bundle."
fi

# Upload MECA bundle to GitHub Release (too large for repo, >100 MB)
MECA_RELEASE_TAG="meca-bundle"
MECA_REPO="quarcs-lab/project2025s"
MECA_URL="https://github.com/${MECA_REPO}/releases/download/${MECA_RELEASE_TAG}/index-meca.zip"

if [ -f index-meca.zip ]; then
  echo "  Uploading MECA bundle to GitHub Release..."
  # Create release if it doesn't exist, or upload/overwrite the asset
  gh release view "$MECA_RELEASE_TAG" --repo "$MECA_REPO" >/dev/null 2>&1 || \
    gh release create "$MECA_RELEASE_TAG" --repo "$MECA_REPO" \
      --title "MECA Bundle" \
      --notes "Auto-updated MECA bundle for manuscript exchange. Generated by clean-render.sh."
  gh release upload "$MECA_RELEASE_TAG" index-meca.zip --repo "$MECA_REPO" --clobber
  echo "  Uploaded to ${MECA_URL}"

  # Update MECA link in HTML to point to the release
  if [ -f index.html ]; then
    sed -i '' "s|href=\"index-meca.zip\"|href=\"${MECA_URL}\"|g" index.html
    echo "  Updated MECA link in index.html"
  fi
fi

echo "Done."
