#!/usr/bin/env bash
# clean-render.sh — Clear all Quarto caches and re-render the manuscript
#
# Pipeline:
#   1. Clear all Quarto caches and intermediates
#   2. Full manuscript render (HTML + notebook previews + all formats)
#   3. Re-render REGION PDF (4 LaTeX passes for natbib/region.bst)
#   4. Re-render Standard PDF (restores index.tex as standard LaTeX)
#   5. Strip legacy/ and log/ from MECA bundle
#   6. Upload MECA to GitHub Release (tag: meca-bundle)
#   7. Update MECA link in index.html to point to release URL
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth login)
#
# Use this when:
#   - Underlying data files changed but notebook source didn't
#   - Embed previews are stale despite source changes
#   - You want a guaranteed clean build
set -euo pipefail
cd "$(dirname "$0")/.."

echo "Cleaning Quarto caches..."
rm -rf _freeze/
rm -rf .quarto/embed/
rm -rf .quarto/_freeze/
rm -f notebooks/*.embed-preview.html
rm -rf notebooks/*.embed_files/
rm -f notebooks/*.out.ipynb
rm -f notebooks/*-preview.html

echo "Rendering manuscript..."

# Step 1: Full manuscript render (generates notebook preview pages + all formats)
# In Quarto manuscript projects, notebook preview HTML pages (the rendered notebooks
# that readers click on) are ONLY generated during a full project render — not when
# using --to flags. This step produces everything but REGION PDF gets only 2 LaTeX
# passes (insufficient for natbib/region.bst), which is fixed in step 2.
echo "  [1/3] Full manuscript render (HTML + notebook previews + all formats)..."
quarto render index.qmd

# Step 2: Re-render REGION PDF with 4 LaTeX passes (fixes natbib/region.bst)
# The full render in step 1 only gives REGION 2 passes, breaking bibliography.
echo "  [2/3] REGION journal PDF (4 passes)..."
quarto render index.qmd --to region-ersa/REGION-pdf
mv index.tex index-REGION.tex

# Step 3: Re-render standard PDF to restore index.tex as standard LaTeX source
# Step 2 overwrote index.tex with REGION LaTeX; this restores it.
echo "  [3/3] Standard PDF (restore LaTeX source)..."
quarto render index.qmd --to pdf

# Strip legacy/ from MECA bundle (too large, not needed for replication)
if [ -f index-meca.zip ]; then
  zip -d index-meca.zip "source/legacy/*" 2>/dev/null || true
  zip -d index-meca.zip "source/log/*" 2>/dev/null || true
  echo "  Stripped legacy/ and log/ from MECA bundle."
fi

# Upload MECA bundle to GitHub Release (too large for repo, >100 MB)
MECA_RELEASE_TAG="meca-bundle"
MECA_REPO="quarcs-lab/project2025s"
MECA_URL="https://github.com/${MECA_REPO}/releases/download/${MECA_RELEASE_TAG}/index-meca.zip"

if [ -f index-meca.zip ]; then
  echo "  Uploading MECA bundle to GitHub Release..."
  # Create release if it doesn't exist, or upload/overwrite the asset
  gh release view "$MECA_RELEASE_TAG" --repo "$MECA_REPO" >/dev/null 2>&1 || \
    gh release create "$MECA_RELEASE_TAG" --repo "$MECA_REPO" \
      --title "MECA Bundle" \
      --notes "Auto-updated MECA bundle for manuscript exchange. Generated by clean-render.sh."
  gh release upload "$MECA_RELEASE_TAG" index-meca.zip --repo "$MECA_REPO" --clobber
  echo "  Uploaded to ${MECA_URL}"

  # Update MECA link in HTML to point to the release
  if [ -f index.html ]; then
    sed -i '' "s|href=\"index-meca.zip\"|href=\"${MECA_URL}\"|g" index.html
    echo "  Updated MECA link in index.html"
  fi
fi

echo "Done."
